name: update

on:
  schedule:
    - cron: '37 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          pip install pipenv
          pipenv install --ignore-pipfile
      - name: update map data
        run: pipenv run python main.py
      - name: commit
        run: ./.github/workflows/git.sh
