name: update

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          pip install pipenv
          pipenv install --ignore-pipfile
      - name: update map data
        run: pipenv run python main.py
      - name: commit
        run: |
          if [[ `git status --porcelain` ]]
          then
            git config --local user.email "mgwalker@users.noreply.github.com"
            git config --local user.name "automatic update"
            git commit -m "regular update" -a
            git remote set-url --push origin https://mgwalker:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
          fi
